title: fullstackopensource.com

plugins: 
  - jemoji

remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    github:  crftbt/FullStackOpenSource
    reddit: FullStackOpenSource
    
titles_from_headings:
  enabled:     false
  strip_title: true
  collections: false

